theme = "cyberpunk-scarlet-protocol"
confirm-before-quit = false
padding-x = 10
padding-y = [15, 10]

[editor]
program = "zed"
args = []

[cursor]
shape = 'block'

[navigation]
mode = "Tab"
hide-if-single = false

[window]
width = 1024
height = 768
opacity = 0.9
opacity-cells = true
blur = true
decorations = "disabled"
windows-corner-preference = "Round"
windows-use-undecorated-shadow = false
windows-use-no-redirection-bitmap = false

[shell]
program = "nu"
args = []

[renderer]
performance = "high"

[title]
content = "{{ TITLE || PROGRAM }}"

[fonts]
# use-drawable-chars = true
family = "JetBrainsMono Nerd Font"
features = ["ss02", "ss03", "ss05", "ss19"]
regular = { style = "Regular", weight = 400 }
bold = { style = "Bold", weight = 700 }
italic = { style = "Italic", weight = 400 }
